#!/usr/bin/env bash
# ----------------------------------------------------------
#  analysis – read clean TSV on stdin, print answers
# ----------------------------------------------------------
TAB=$'\t'
awk -v FS="$TAB" '
function trim(s){sub(/^[ \t]+/,"",s);sub(/[ \t]+$/,"",s);return s}

NR==1 {                                  # header -> remember field numbers
    for(i=1;i<=NF;i++){
            if($i=="Year Published")  cYear=i
                    else if($i=="Rating Average") cRate=i
                            else if($i=="Complexity Average") cComp=i
                                    else if($i=="Mechanics") cMech=i
                                            else if($i=="Domains") cDom=i
                                                }
                                                    next
                                                    }

                                                    # ---------- Popularity counts ----------
                                                    {
                                                        # Mechanics (may be empty)
                                                            n = split($cMech, tmp, ",")
                                                                for (i=1;i<=n;i++) {
                                                                        val = trim(tmp[i])
                                                                                if(val!="") mech[val]++
                                                                                    }

                                                                                        # Domains
                                                                                            n = split($cDom, tmp, ",")
                                                                                                for (i=1;i<=n;i++) {
                                                                                                        val = trim(tmp[i])
                                                                                                                if(val!="") dom[val]++
                                                                                                                    }

                                                                                                                        # ---------- correlation accumulations ----------
                                                                                                                            yr   = $cYear + 0
                                                                                                                                rate = $cRate + 0
                                                                                                                                    comp = $cComp + 0

                                                                                                                                        nY++
                                                                                                                                            sumYr += yr
                                                                                                                                                sumRate += rate
                                                                                                                                                    sumYr2 += yr*yr
                                                                                                                                                        sumRate2 += rate*rate
                                                                                                                                                            sumYrRate += yr*rate

                                                                                                                                                                nC++
                                                                                                                                                                    sumComp += comp
                                                                                                                                                                        sumComp2 += comp*comp
                                                                                                                                                                            sumCompRate += comp*rate
                                                                                                                                                                            }

                                                                                                                                                                            END {
                                                                                                                                                                                # ---- most popular mechanics / domain ----
                                                                                                                                                                                    for (m in mech) if(mech[m]>mechMax){mechMax=mech[m]; bestMech=m}
                                                                                                                                                                                        for (d in dom) if(dom[d]>domMax){domMax=dom[d]; bestDom=d}

                                                                                                                                                                                            printf "The most popular game mechanics is %s found in %d games\n", bestMech, mechMax
                                                                                                                                                                                                printf "The most popular game domain is %s found in %d games\n\n", bestDom, domMax

                                                                                                                                                                                                    # ---- correlations ----
                                                                                                                                                                                                        rYr = (nY*sumYrRate - sumYr*sumRate) / sqrt((nY*sumYr2 - sumYr^2)*(nY*sumRate2 - sumRate^2))
                                                                                                                                                                                                            rComp = (nC*sumCompRate - sumComp*sumRate) / sqrt((nC*sumComp2 - sumComp^2)*(nC*sumRate2 - sumRate^2))

                                                                                                                                                                                                                printf "The correlation between the year of publication and the average rating is %.3f\n", rYr
                                                                                                                                                                                                                    printf "The correlation between the complexity of a game and its average rating is %.3f\n", rComp
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    '
