#!/usr/bin/env bash
#############################################################
# Author: Bhavik Mistry
# Student Number: 23841008
# Purpose: Count the empty cells in every column.
# How to run: ./empty_cells bgg_dataset.txt ';'
#############################################################

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <file> <separator>" >&2
    exit 1
    fi

if [ ! -r "$1" ]; then
      echo "Error: cannot read '$1'" >&2
        exit 1
fi

    FILE="$1"
    SEP="$2"

    tr -d '\r' < "$FILE" | awk -v FS="$SEP" '
    NR==1 {
        # record header and number of columns
            ncol = NF
                for (i=1; i<=NF; i++) hdr[i] = $i
                    next
                    }
                    {
                        # count blanks in each field up to ncol
                            for (i=1; i<=ncol; i++)
                                    if ($i == "") cnt[i]++
                                    }
                                    END {
                                        # print header[i] : count
                                            for (i=1; i<=ncol; i++)
                                                    printf "%s: %d\n", hdr[i], cnt[i]+0
                                                    }
                                                    '

